test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocBuilder.kt

Spring Rest Doc DSL 사용시 request와 response에 특별한 스펙이 없는 테스트에서 에러를 발생하는 문제를 해결하기 위해서 snippet이 전혀 없는 테스트 케이스를 작성하더라도 에러가 발생하지 않도록 변경하였습니다.

bug : snippet 없을 때, 에러 발생

---

test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocBuilder.kt

#24 
mockMvc를 통한 rest docs 생성시 버그를 수정했습니다.

fix : mockMvc dsl 연동 버그

---

user/src/main/kotlin/kpring/user/controller/ExceptionController.java
user/src/main/kotlin/kpring/user/controller/UserController.kt
user/src/main/kotlin/kpring/user/dto/result/FailMessageResponse.java
user/src/main/kotlin/kpring/user/dto/result/UpdateUserProfileResponse.java
user/src/main/kotlin/kpring/user/exception/ErrorCode.java
user/src/test/kotlin/kpring/user/controller/UserControllerTest.kt

#21 
회원정보 수정 API 실패 테스트를 작성했어요.
* 권한이 없는 토큰 사용시 403
* 서버 내부 오류 발생시 500
AuthClient를 통해서 Auth 서버를 호출하는 코드가 추가되었어요.

[user] 회원정보 수정 API 실패 테스트

---

auth/src/main/kotlin/kpring/auth/api/v1/AuthController.kt
auth/src/main/kotlin/kpring/auth/service/TokenService.kt
auth/src/test/kotlin/kpring/auth/api/AuthControllerTest.kt
auth/src/test/kotlin/kpring/auth/service/TokenServiceTest.kt
core/src/main/kotlin/kpring/core/auth/dto/request/TokenValidationRequest.kt
core/src/main/kotlin/kpring/core/auth/dto/response/TokenValidationResponse.kt

#14 
채팅 생성시 토큰으로 부터 유저의 id를 조회하기 위해서 토큰 검증 API의 스펙을 변경하였습니다.
Request body에 입력받은 userId를 통해서 토큰의 userId 정보와 일치하는지를 검사했던 기능을
현재는 토큰이 정상적으로 발급되었는지 만료되지 않았는지를 검사하여 유효성을 확인하고 토큰에 저장된 userId와 타입을 응답합니다.

[Auth] validation API 스펙 변경

---

build.gradle.kts
chat/build.gradle.kts
chat/compose.yml
chat/src/main/kotlin/kpring/chat/chat/model/Chat.kt
chat/src/main/kotlin/kpring/chat/chat/repository/ChatRepository.kt
chat/src/test/kotlin/kpring/chat/example/SampleTest.kt

#43 
동적 쿼리 생성을 위해서 queryDsl 관련 설정을 추가했습니다.
ChatRepository를 통해서 queryDsl을 사용하는 예시 테스트를 작성하였습니다.
spring data 프로젝트에서 지원하는 QuerydslPrdicateExecutor를 상속받아 생성된 Qclass를 활용하는 방식으로 구현해보았습니다! 현재 구조에서는 객체를 포함하는 엔티티가 없기 때문에 현재 알아낸 방법으로 충분히 개발이 가능할 것 같아요!
queryDsl 예시 테스트 코드에서 작성된 예시의 코드 퀄리티에 대해서 궁금합니다.
https://github.com/404-nut-pound/spring-mongodb-querydsl-template
https://github.com/spring-projects/spring-data-examples/blob/main/mongodb/querydsl/README.md

[Chat] queryDsl mongo 설정 및 셈플 코드 작성

---

server/src/main/kotlin/kpring/server/adapter/input/rest/RestApiServerController.kt
server/src/test/kotlin/kpring/server/adapter/input/rest/RestApiServerControllerTest.kt
server/src/test/kotlin/kpring/server/application/port/output/GetServerPortTest.kt

> #75 
- 서버 생성 api 성공시 테스트 구현
- 서버 생성 api 실패(존재하지 않은 serverId 사용시) 테스트 구현
- 서버 조회 포트(repository) 인터페이스 테스트 구현 (존재하지 않은 serverId 사용시)

[Server] 서버 생성 API 테스트 추가

---

front/src/App.tsx
front/src/components/Auth/JoinBox.tsx
front/src/components/Auth/LoginBox.tsx
front/src/pages/Join.tsx

- 없음
1. 로그인 페이지 디자인 수정
- 좀 더 이쁘게 수정했습니다.  배경이 반투명이라서 전체 배경 넣어도 이쁠 것 같습니다.
2. 회원가입 페이지 추가와  UI 렌더링
- router에도 연결해두고, UI를 만들었습니다. 
3. 로그인과 회원가입 버튼 서로 연결 해뒀습니다.
- 로그인 페이지에서 회원가입 버튼을 누르면 회원가입 페이지로 이동
- 회원가입 페이지에서 로그인 하러가기 버튼 누르면 로그인 페이지로 이동
> API 명세를 보니 유저이름과 이메일, 비밀번호만 있는것 같던데 혹시 추가 해야할 것이 있을까요? 
> 1차적인 UI 이므로 변동 될 가능성 있습니다.

Feat/auth 회원가입 페이지 UI 렌더링 + 그 외

---

front/src/components/Auth/JoinBox.tsx
front/src/components/Auth/LoginBox.tsx
front/src/components/Layout/Layout.tsx
front/src/hooks/JoinValidation.ts
front/src/pages/Join.tsx
front/src/pages/Login.tsx
front/src/theme/themeConfig.ts
front/src/types/join.ts

🎈
-  Mui의 중복되는 테마 코드를 하나로 이동하였습니다. (themeConfig.ts)
- input 요소가 autocomplete 속성을 가지지 않아 발생하는 경고이므로 속성을 추가해주면 됩니다. 해결완료! 
아래와 같은 메세지로 출력됩니다.
1번째. 닉네임
1) 빈 칸인 경우 : 닉네임을 입력해주세요.
2) 닉네임이 최소 2글자가 아닌 경우 : 닉네임은 최소 2글자 이상이어야 합니다.
2번째. 이메일
1) 빈 칸인 경우 : 이메일을 입력해주세요.
2) 이메일 형식이 아닌 경우 : 올바른 이메일 형식이 아닙니다.
3번째. 비밀번호
1) 빈 칸인 경우 : 비밀번호를 입력해주세요.
2) 비밀번호 규칙에 안 맞는 경우 : 비밀번호는 소문자, 숫자, 특수문자를 포함한 8자 이상이어야 합니다.
4번째. 비밀번호 확인
1) 빈 칸인 경우 : 비밀번호 확인을 입력해주세요.
2) 비밀번호와 동일하지 않는 경우 : 비밀번호가 일치하지 않습니다.
==========================================================\
1) 비밀번호는 최소 8자에서 15자 사이
2) 대문자, 소문자, 숫자가 포함되어야함
3) 특수문자 ! @ # $ 도 사용 가능
```
export type JoinBoxValues = {
nickname: string;
email: string;
password: string;
passwordConfirm: string;
};
export type JoinBoxValidateErrors = {
nicknameError: string;
emailError: string; …
```

Feat/auth 테마 코드 이동, autocomplete Warning 해결, 회원가입 유효성 검사 추가

---

core/src/main/kotlin/kpring/core/server/dto/request/GetServerCondition.kt
server/src/main/kotlin/kpring/server/adapter/input/rest/RestApiServerController.kt
server/src/main/kotlin/kpring/server/adapter/output/mongo/GetServerProfileMongoImpl.kt
server/src/main/kotlin/kpring/server/application/port/input/GetServerInfoUseCase.kt
server/src/main/kotlin/kpring/server/application/port/output/GetServerProfilePort.kt
server/src/main/kotlin/kpring/server/application/service/ServerService.kt
server/src/test/kotlin/kpring/server/adapter/input/rest/RestApiServerControllerTest.kt
server/src/test/kotlin/kpring/server/application/port/output/GetServerProfilePortTest.kt
test/src/main/kotlin/kpring/test/web/URLBuilder.kt
test/src/test/kotlin/test/web/URLBuilderTest.kt

- #123
- 서버 목록 조회시 조건을 추가하여 #123 이슈에 필요한 데이터만을 조회할 수 있도록 조건을 추가하였습니다.
- controller 테스트에서 query param를 입력하기 위한 test util 클래스를 생성하였습니다.
- serverIds : 조건을 입력하면 입력한 서버 id 목록에 존재하는 서버 정보를 반환합니다.

[Server] 서버 목록 조회 검색 조건 기능 추가

---

test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocMultipartFieldBuilder.kt
test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocRequestBuilder.kt

- #127
request part에 object를 담았을 때 세부 사항에 대한 문서화 기능을 제공하지 않았습니다.
때문에 이 기능을 제공하도록 커스텀 dsl을 확장하였습니다.

[Test] request part object 문서화를 위한 custom dsl 기능 추가

---

front/src/components/Chat/ChatRoomSideBar.tsx
front/src/components/Layout/DropDown.tsx
front/src/components/Layout/FriendsRightSideBar.tsx
front/src/components/Layout/Header.tsx
front/src/components/Layout/MemberList.tsx
front/src/components/Layout/MemberListItem.tsx
front/src/components/Layout/MessageRightSideBar.tsx
front/src/store/useChatRoomStore.ts
front/src/types/layout.ts
front/src/utils/fakeData.ts
front/tailwind.config.js

- 사이드바 UI 수정(색상 및 배치)
- 사이드바 MemberList 컴포넌트 분리 : 유지보수 및 가독성
- 드롭다운 컴포넌트 생성
- 채팅방 컴포넌트 생성 및 연결
제가 작업 파일이 지현님과 겹치는 부분이 있어서 충돌 발생 or 꼬일까봐 PR 타이밍을 많이 놓쳤습니다
제가 비교하긴 했는데 혹시 최근에 본인이 작업했던 코드가 없어지지는 않았는지 확인 부탁드립니다

[CHAT] 사이드바 UI 수정 및 채팅방 컴포넌트 생성

---

front/src/components/Auth/JoinBox.tsx
front/src/types/join.ts

> 없음
- 현재 사용중인 UI 라이브러리인 Mui의 alert를 구현했습니다.
1) 회원가입 성공인 경우
- 3초 후 자동으로 로그인 페이지로 이동합니다.
2) 회원가입 실패인 경우
**- 커밋 메세지나 위의 제목이 적당한것을 찾지 못해서 일단 적었습니다만.. **
- 쉽게 말해서 이미 사용중인 이메일의 경우 아래처럼 알림이 뜹니다. 
- 구현 원리는 이미 사용중인 이메일을 입력하면 서버로부터 "Email already exists" 메세지가 오는데, 그 텍스트를 기반으로 "이미 존재하는 이메일입니다. 다시 시도해주세요."로 변경되도록 했습니다. 
- Swagger UI를 봤는데.. 프론트 단에서 이메일이 빈칸인 경우 회원가입이 불가능하도록 해서 일단 에러 메세지는.. 이메일 중복에 대한 에러만 처리해뒀는데 별도의 또 다른 에러가 있을까요?  현재는 이메일 중복을 제외한 모든 오류는 "회원가입 과정에서 문제가 발생했습니다."로 처리해두었습니다.
♣ 참조한 Mui alert : https://mui.com/material-ui/react-alert/

Feat/auth 회원가입 페이지의 Mui Alert와 이메일 중복 에러메세지 구현

---

auth/build.gradle.kts
infra/charts/auth/values.yaml
infra/charts/server/values.yaml
infra/charts/user/values.yaml
server/build.gradle.kts
user/build.gradle.kts

- image registry로 docker hub를 이용하도록 하여 빌드 과정을 단축시켰습니다.
- `./gradlew jib` 과정을 이제는 하지 않아도 어플리케이션을 배포할 수 있습니다.
[이미지 저장 목록](https://hub.docker.com/repositories/youdong98)

[Infra] image registry 변경 

---

server/src/main/kotlin/kpring/server/adapter/output/mongo/entity/ServerProfileEntity.kt
server/src/main/resources/application.yml

- 배포 환경에서 mongodb에 권한이 없어서 접속이 실패하는 버그를 수정했습니다.
- 서버 생성시 서버 프로필의 id가 "userId"로 고정되어 생성되어 server profile 이 저장되지 않던 버그를 수정했습니다.

[Server] 서버 버그 수정

---

core/src/main/kotlin/kpring/core/server/dto/CategoryInfo.kt
server/src/main/kotlin/kpring/server/adapter/input/rest/CategoryController.kt
server/src/main/kotlin/kpring/server/application/port/input/GetCategoryUseCase.kt
server/src/main/kotlin/kpring/server/application/service/CategoryService.kt
server/src/main/kotlin/kpring/server/domain/Category.kt
server/src/test/kotlin/kpring/server/adapter/input/rest/CategoryControllerTest.kt
server/src/test/kotlin/kpring/server/adapter/input/rest/RestApiServerControllerTest.kt
server/src/test/kotlin/kpring/server/application/service/CategoryServiceTest.kt
test/src/main/kotlin/kpring/test/web/MvcWebTestClientDescribeSpec.kt
test/src/main/kotlin/kpring/test/web/WebTestClientDescribeSpec.kt

- #159 
서버의 카테고리 기능이 추가되면서 카테고리 목록조회에 대한 기능을 구현하였습니다.
카테고리 기능을 활용하는 추가적인 기능이 없기 때문에 하드코딩한 카테고리 목록을 사용하는 방식으로 구현하였습니다.

[Server] 카테고리 조회 API 구현

---

core/src/main/kotlin/kpring/core/server/dto/ServerThemeInfo.kt
core/src/main/kotlin/kpring/core/server/dto/request/CreateServerRequest.kt
core/src/main/kotlin/kpring/core/server/dto/response/CreateServerResponse.kt
server/src/main/kotlin/kpring/server/adapter/input/rest/RestApiServerController.kt
server/src/main/kotlin/kpring/server/adapter/output/mongo/GetServerPortMongoImpl.kt
server/src/main/kotlin/kpring/server/adapter/output/mongo/GetServerProfileMongoImpl.kt
server/src/main/kotlin/kpring/server/adapter/output/mongo/SaveServerPortMongoImpl.kt
server/src/main/kotlin/kpring/server/adapter/output/mongo/entity/ServerEntity.kt
server/src/main/kotlin/kpring/server/adapter/output/mongo/entity/ServerProfileEntity.kt
server/src/main/kotlin/kpring/server/application/port/input/CreateServerUseCase.kt
server/src/main/kotlin/kpring/server/application/port/output/SaveServerPort.kt
server/src/main/kotlin/kpring/server/application/service/ServerService.kt
server/src/main/kotlin/kpring/server/domain/Server.kt
server/src/main/kotlin/kpring/server/domain/ServerProfile.kt
server/src/main/kotlin/kpring/server/domain/Theme.kt
server/src/main/kotlin/kpring/server/error/ServerErrorCode.kt
server/src/main/kotlin/kpring/server/util/DtoMapper.kt
server/src/test/kotlin/kpring/server/adapter/input/rest/RestApiServerControllerTest.kt
server/src/test/kotlin/kpring/server/application/port/input/AddUserAtServerUseCaseTest.kt
server/src/test/kotlin/kpring/server/application/port/input/DeleteServerUseCaseTest.kt
server/src/test/kotlin/kpring/server/application/port/output/GetServerPortTest.kt
server/src/test/kotlin/kpring/server/application/port/output/GetServerProfilePortTest.kt
server/src/test/kotlin/kpring/server/application/port/output/SaveServerPortTest.kt
server/src/test/kotlin/kpring/server/application/port/output/UpdateServerPortTest.kt
server/src/test/kotlin/kpring/server/domain/ServerProfileTest.kt
server/src/test/kotlin/kpring/server/domain/ServerTest.kt
test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocBodyBuilder.kt

- #159 
- 도메인의 제약을 엔티디에서 반영하도록 리펙터링을 진행하였습니다.
- 서버 생성시 테마와 카테고리를 설정하도록 기능을 확장하였습니다.

[Server] 서버 생성 : 테마, 카테고리 입력 확장

---

.github/workflows/ci.yml

- #182 
-  argoCD를 이용한 CD 작업을 위해서 이미지의 버전을 깃 커밋 해시로 관리하는 액션을 추가했습니다.

[infra] image tag 정보 갱신을 위한 git action 수정

---

user/src/main/kotlin/kpring/user/controller/FriendController.kt
user/src/main/kotlin/kpring/user/entity/Friend.kt
user/src/main/kotlin/kpring/user/exception/UserErrorCode.kt
user/src/main/kotlin/kpring/user/repository/FriendRepository.kt
user/src/main/kotlin/kpring/user/service/FriendService.kt
user/src/main/kotlin/kpring/user/service/FriendServiceImpl.kt
user/src/test/kotlin/kpring/user/controller/FriendControllerTest.kt
user/src/test/kotlin/kpring/user/service/FriendServiceImplTest.kt

- #180 
- 친구신청 수락 API 구현하였습니다.
- 친구신청 수락 관련 Controller 테스트코드를 작성하였습니다.
- 친구신청 수락 관련 Service 테스트코드를 작성하였습니다.

[User] 친구 신청 수락 API 구현

---

front/src/components/Auth/JoinBox.tsx
front/src/components/Auth/LoginBox.tsx
front/src/store/useLoginStore.ts

> 없음
> 
1. 로그인이 됩니다.
이메일과 비밀번호를 정확하게 입력할 경우 서버로부터 위와 같은 응답을 받습니다. 
현재  alert로 해뒀지만 곧 mui alert로 변경할 예정입니다.
일단 토큰은 local 스토리지에 저장되도록 했습니다. 
현재 코드는 로그인 성공과 실패만 콘솔로그가 찍힙니다. 폼제출 시도나 토큰설정은 주석처리해뒀습니다. 
2.  회원가입 API 주소 변경을 했습니다.
API 주소가 바뀜에 따라 주소를 변경했고 정상적으로 회원가입이 됩니다. 
위에 첨부
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
> 코드가 단순하게 느껴지실지는 모르겠지만 일단 1차적으로 구현을 하고 좀더 좋게 리팩토링 할 예정입니다.

Feat/auth 로그인이 되는 것과 회원가입 API 주소 변경

---

user/src/main/java/kpring/user/dto/response/DeleteFriendResponse.java
user/src/main/kotlin/kpring/user/dto/response/DeleteFriendResponse.kt
user/src/main/kotlin/kpring/user/entity/User.kt
user/src/main/kotlin/kpring/user/exception/UserErrorCode.kt
user/src/main/kotlin/kpring/user/repository/FriendRepository.kt
user/src/main/kotlin/kpring/user/service/FriendService.kt
user/src/main/kotlin/kpring/user/service/FriendServiceImpl.kt
user/src/test/kotlin/kpring/user/controller/FriendControllerTest.kt
user/src/test/kotlin/kpring/user/service/FriendServiceImplTest.kt

- #193 
- 친구삭제 API 구현하였습니다.
- 친구삭제 관련 Controller 테스트코드를 작성하였습니다.
- 친구삭제 관련 Service 테스트코드를 작성하였습니다.

[User] 친구삭제 API 구현

---

user/src/main/java/kpring/user/dto/response/GetFriendsResponse.java
user/src/main/kotlin/kpring/user/dto/response/GetFriendResponse.kt
user/src/main/kotlin/kpring/user/dto/response/GetFriendsResponse.kt
user/src/main/kotlin/kpring/user/service/FriendService.kt
user/src/main/kotlin/kpring/user/service/FriendServiceImpl.kt
user/src/test/kotlin/kpring/user/controller/FriendControllerTest.kt
user/src/test/kotlin/kpring/user/global/CommonTest.kt
user/src/test/kotlin/kpring/user/service/FriendServiceImplTest.kt
user/src/test/kotlin/kpring/user/service/UserServiceImplTest.kt

- #198 
- 친구목록 조회 API 를 구현하였습니다.
- 친구목록 조회 Controller 테스트코드를 작성하였습니다.
- 친구목록 조회 Service 테스트코드를 작성하였습니다.

[User] 친구목록 조회 API 구현

---

.github/workflows/ci.yml

- #209 
- swagger에서 authorization 헤더가 작동하지 않아서 요청을 활용하지 못하는 불편사항을 개선하였습니다.
- 생성된 openapi3.yaml을 ci 과정에서 수정하여 모든 api 요청에 authorization 헤더를 적용하였습니다.
- 필요없는 요청에 대해서도 authorization 헤더가 적용되는 한계점이 있지만 기존에 작동하지 않은 Authorization 스펙 문서를 통해서 필요한 api를 구분하고 요청을 테스트하는 것이 중요하다는 생각에 현재 구현 방식을 체택하였습니다.

[Infra] swagger Authorization 헤더 주입 실패 현상 개선

---

front/.gitignore
front/src/api/axiosInstance.ts
front/src/components/Auth/AuthLayout.tsx
front/src/components/Auth/JoinBox.tsx
front/src/components/Auth/LoginBox.tsx
front/src/hooks/FetchServer.ts
front/src/hooks/UpdatedServer.ts

1. API 요청하는 주소를 환경변수 설정했습니다
2. 로그인 페이지에서 비밀번호 보이기/ 감추기 기능 구현
- 아래 이미지로 설명을 대체하겠습니다.
3. 로그인 페이지 진입시 로딩 인디케이터 구현
- 첨부한 이미지는 이미 로그인 중이기 때문에 로딩 인디케이터만  뜨고 메인페이지로 리디렉션됩니다.
- 로딩 인디케이터가 어떤식으로 뜨는지 보여드리 위한 참고 이미지입니다. 
FetchServer.ts와 UpdatedServer.ts는 @jihyun-j 님이 작성하신 코드여서 일단 DM 드린것 처럼 https로만 수정해두었습니다!
추후 원하실때 환경변수화 하시는것을 추천드립니다!

[Feat/auth] 로그인 페이지 비밀번호 보이기/감추기, 로딩 인디케이터, 환경변수 설정

---

server/src/main/kotlin/kpring/server/adapter/output/mongo/DeleteServerPortMongoImpl.kt
server/src/main/kotlin/kpring/server/adapter/output/mongo/repository/ServerProfileRepository.kt
server/src/test/kotlin/kpring/server/adapter/output/mongo/repository/ServerProfileRepositoryTest.kt

- #228 
- 서버 삭제시 관련된 프로필을 삭제하지 않기 때문에 발생한 버그를 수정하였습니다.
- 서버 프로필 일괄 삭제를 위한 기능을 추가하였습니다.
- 서버의 ID와 연관된 서버 프로필을 일괄 삭제할 수 있습니다.

서버 삭제 기능 버그 수정

---

core/src/main/kotlin/kpring/core/server/dto/request/UpdateHostAtServerRequest.kt
server/src/main/kotlin/kpring/server/adapter/input/rest/RestApiServerController.kt
server/src/main/kotlin/kpring/server/adapter/output/mongo/UpdateServerPortMongoImpl.kt
server/src/main/kotlin/kpring/server/adapter/output/mongo/UpdateServerProfilePortMongoImpl.kt
server/src/main/kotlin/kpring/server/application/port/input/UpdateHostAtServerUseCase.kt
server/src/main/kotlin/kpring/server/application/port/output/UpdateServerPort.kt
server/src/main/kotlin/kpring/server/application/port/output/UpdateServerProfilePort.kt
server/src/main/kotlin/kpring/server/application/service/ServerService.kt
server/src/main/kotlin/kpring/server/domain/Server.kt
server/src/main/kotlin/kpring/server/domain/ServerHost.kt
server/src/main/kotlin/kpring/server/domain/ServerProfile.kt
server/src/test/kotlin/kpring/server/adapter/input/rest/RestApiServerControllerTest.kt
server/src/test/kotlin/kpring/server/application/port/input/AddUserAtServerUseCaseTest.kt
server/src/test/kotlin/kpring/server/application/port/input/DeleteServerUseCaseTest.kt
server/src/test/kotlin/kpring/server/application/port/output/UpdateServerPortTest.kt

- 로그인한 사용자가 서버에 있는 다른 사용자에게 서버의 호스트 권한을 상속하는 API 를 구현하였습니다.
- 서버장 권한 상속 Controller 테스트코드를 작성하였습니다.
- 서버장 권한 상속 Service 테스트코드를 작성하였습니다.

[Server] 서버장 권한 상속 API 구현

---

user/src/main/java/kpring/user/dto/response/GetUserProfileResponse.java
user/src/main/kotlin/kpring/user/service/UserServiceImpl.kt
user/src/test/kotlin/kpring/user/controller/UserControllerTest.kt

- 프로필 조회 시 프로필 사진도 조회 가능하도록 코드 수정
- 프로필 조회 controller 테스트 코드 수정

[User] 프로필조회 시 프로필사진 조회 기능 추가

---

server/src/main/kotlin/kpring/server/adapter/input/rest/RestApiServerController.kt
server/src/main/kotlin/kpring/server/adapter/output/mongo/DeleteServerPortMongoImpl.kt
server/src/main/kotlin/kpring/server/adapter/output/mongo/repository/ServerProfileRepository.kt
server/src/main/kotlin/kpring/server/application/port/input/DeleteServerUseCase.kt
server/src/main/kotlin/kpring/server/application/port/output/DeleteServerPort.kt
server/src/main/kotlin/kpring/server/application/service/ServerService.kt
server/src/test/kotlin/kpring/server/adapter/input/rest/RestApiServerControllerTest.kt

- #247 
- 서버 탈퇴 API 기능 구현
- 서버 탈퇴 controller 테스트코드 작성

[Server] 서버 탈퇴 API 기능 구현

---

chat/src/main/kotlin/kpring/chat/chat/api/v1/ChatController.kt
chat/src/main/kotlin/kpring/chat/global/config/WebSocketConfig.kt

close #278
- 채팅방 나가기를 한 유저에게 메시지가 전송되지 않도록 인터셉터의 preSend 메서드에서 메시지 송수신시 권한 확인을 하는 로직을 추가했습니다.
- 기존 인터셉터 코드가 한 메서드 안에 너무 길게 작성되어 있어 메서드를 분리해 코드를 정리했습니다.

[Chat] 채팅방에 Event가 일어났을 때 해당 채팅방을 구독하는 사용자들에게 보내기

---

chat/src/main/kotlin/kpring/chat/chatroom/api/v1/WebSocketChatRoomController.kt
chat/src/main/kotlin/kpring/chat/chatroom/model/EventType.kt
chat/src/main/kotlin/kpring/chat/chatroom/repository/ChatRoomRepository.kt
chat/src/main/kotlin/kpring/chat/chatroom/service/ChatRoomService.kt
chat/src/main/kotlin/kpring/chat/global/exception/ErrorCode.kt
chat/src/main/kotlin/kpring/chat/global/util/AccessVerifier.kt
chat/src/main/resources/static/chatSample.html
chat/src/test/kotlin/kpring/chat/chatroom/ChatRoomServiceTest.kt
core/src/main/kotlin/kpring/core/chat/chatroom/dto/request/ExpelChatRoomRequest.kt

- close #288
- 채팅방에서 방장이 유저를 내보내는 기능을 구현했습니다
이 부분 테스트를 원래는 다음과 같이 어떤 에러가 나는지 명시하고 있었습니다
```
test("방장이 아닌 사용자가 추방을 시도하면 예외가 발생해야 한다") {
// Given
val chatRoomId = ContextTest.TEST_ROOM_ID
val userId = "non_owner_user"
val expelUserId = "user_to_expel"
val request = ExpelChatRoomRequest(chatRoomId, expelUserId)
// 예외 모킹 시 예외 코드 지정
every { accessVerifier.verifyChatRoomOwner(chatRoomId, userId) } throws GlobalException(ErrorCode.FORBIDDEN_CHATROOM)
// When & Then
val exception =
shouldThrow<GlobalException> {
chatRoomService.expelFromChatRoom(request, userId)
}
exception.getErrorCode() shouldBe ErrorCode.FORBIDDEN_CHATROOM // 예외 코드 확인
}
```
자꾸 MockException이 떠서
```
java.lang.AssertionError: Expected exception kpring.chat.global.exception.GlobalException but a MockKException was thrown instead. …
```

[Chat] 채팅방에서 유저 추방하기

---

chat/src/main/resources/application.yml

- close #308
ServerClientConfig 에서 배포 환경일 때에 올바른 yaml파일을 읽지 않아서 UserController가 깨지는 문제 수정
ServerClientConfig.kt에서
```kotlin
@Value("\${url.server}")
private lateinit var serverUrl: String
```
이 부분에서
원래 두번째 것을 읽어야 하는데 첫번째 것을 읽어서 생기는 문제를 해결하였습니다!
@yudonggeun 님이 infra 설정의 helm 차트에 Server의 url을 등록하고
https://github.com/kSideProject/kpring-infra/blob/main/charts/user/templates/deployment.yaml
```bash
{{- if .Values.global.enable.user }}
apiVersion: apps/v1
kind: Deployment
metadata:
name: {{ .Values.service.name }}
namespace: {{ .Release.namespace }}
labels:
app: {{ .Values.service.name }}
spec:
replicas: 1
selector:
matchLabels:
app: {{ .Values.service.name }}
template:
metadata:
labels:
app: {{ .Values.service.name }}
spec:
containers:
- name: {{ .Values.service.name }}
image: {{ …
```

fix: server url을 infra 설정의 helm chart에 매핑된 value로 수정

---

user/src/main/resources/application.yaml

server url을 user module의 application.yaml에 추가해 운영 환경에서 UserController에 주입할 ServerClientConfig Bean이 생성이 깨지는 문제를 해결했습니다.

fix: user module의 application.yaml에 server url 추가

---

core/src/main/kotlin/kpring/core/global/config/WebFluxStaticResourceConfig.kt
core/src/main/kotlin/kpring/core/global/config/WebMvcStaticResourceConfig.kt
user/src/main/kotlin/kpring/user/config/SecurityConfig.kt

- close #312
찾아보니 개발환경에서 front와 back간의 CORS에러를 없앨때는 proxy를 사용하지만
저희처럼 로컬 개발환경 프론트에서 배포된 운영환경 백엔드에 요청을 보내는 경우는 해당하지 않는 것 같아
부득이하게 백엔드에서 cors 설정을 해제했습니다

[Fix] User 모듈에 CORS 설정 추가하여 로컬 프론트엔드 요청 허용
