test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocBuilder.kt
user/build.gradle.kts
user/src/main/kotlin/kpring/user/controller/ExceptionController.java
user/src/main/kotlin/kpring/user/controller/LoginController.kt
user/src/main/kotlin/kpring/user/dto/request/LoginRequest.java
user/src/main/kotlin/kpring/user/dto/request/LogoutRequest.java
user/src/main/kotlin/kpring/user/dto/result/LoginResponse.java
user/src/main/kotlin/kpring/user/service/LoginService.java
user/src/test/kotlin/kpring/user/controller/LoginControllerTest.kt
user/src/test/kotlin/kpring/user/controller/UserControllerTest.kt

#21 
로그인, 로그아웃 컨트롤러 테스트 코드를 작성하였습니다.
Controller 계층에 대한 테스트와 구현을 생성했습니다.

[User] login, logout 테스트 작성

---

user/src/main/kotlin/kpring/user/controller/UserController.kt
user/src/test/kotlin/kpring/user/controller/UserControllerTest.kt

[USER] 회원 탈퇴 API 테스트 케이스 작성

---

core/src/main/kotlin/kpring/core/auth/client/AuthClient.java
user/src/main/kotlin/kpring/user/controller/UserController.kt
user/src/main/kotlin/kpring/user/dto/result/GetUserProfileResponse.java
user/src/main/kotlin/kpring/user/exception/ErrorCode.java
user/src/test/kotlin/kpring/user/controller/UserControllerTest.kt

[USER] 회원 조회 API 테스트 케이스 작성

---

chat/build.gradle.kts
chat/src/main/kotlin/kpring/chat/api/v1/ChatController.kt
chat/src/main/kotlin/kpring/chat/config/ClientConfig.java
chat/src/main/kotlin/kpring/chat/exception/ErrorCode.kt
chat/src/main/kotlin/kpring/chat/exception/GlobalException.kt
chat/src/main/kotlin/kpring/chat/exception/GlobalExceptionHandler.kt
chat/src/main/kotlin/kpring/chat/model/Chat.kt
chat/src/main/kotlin/kpring/chat/repository/ChatRepository.kt
chat/src/main/kotlin/kpring/chat/service/ChatService.kt
chat/src/main/resources/application.properties
chat/src/main/resources/application.yml
core/src/main/kotlin/kpring/core/chat/dto/request/CreateChatRequest.kt
core/src/main/kotlin/kpring/core/chat/dto/response/CreateChatResponse.kt
core/src/main/kotlin/kpring/core/global/dto/response/ApiResponse.kt

[Chat] Feat/create chat

---

chat/src/main/kotlin/kpring/chat/config/ClientConfig.kt

#41 
실수로 변경사항이 커밋되지 않았습니다. #41를 참고해주세요

fix : gradle build 시 unsolved reference 수정

---

auth/src/main/kotlin/kpring/auth/AuthApplication.kt
core/build.gradle.kts
core/src/main/kotlin/kpring/core/global/config/WebFluxStaticResourceConfig.kt
core/src/main/kotlin/kpring/core/global/config/WebMvcStaticResourceConfig.kt
user/src/main/kotlin/kpring/user/UserApplication.kt

#40 
- swagger api에서 요청 생성시 cors 에러가 발생하는 문제를 해결하였습니다.
- local 환경에서 사용하는 `StaticResourceConfig` 설정 클래스를 `core` 모듈로 이동하였습니다.

[Infra] local profile Swagger Cors 허용

---

chat/src/main/kotlin/kpring/chat/chat/api/v1/ChatController.kt
chat/src/main/kotlin/kpring/chat/chat/model/Chat.kt
chat/src/main/kotlin/kpring/chat/chat/repository/ChatRepository.kt
chat/src/main/kotlin/kpring/chat/chat/service/ChatService.kt
chat/src/main/kotlin/kpring/chat/chatroom/api/v1/ChatRoomController.kt
chat/src/main/kotlin/kpring/chat/chatroom/model/ChatRoom.kt
chat/src/main/kotlin/kpring/chat/chatroom/repository/ChatRoomRepository.kt
chat/src/main/kotlin/kpring/chat/chatroom/service/ChatRoomService.kt
chat/src/main/kotlin/kpring/chat/global/config/ClientConfig.kt
chat/src/main/kotlin/kpring/chat/global/exception/ErrorCode.kt
chat/src/main/kotlin/kpring/chat/global/exception/GlobalException.kt
chat/src/main/kotlin/kpring/chat/global/exception/GlobalExceptionHandler.kt
core/src/main/kotlin/kpring/core/chat/chat/dto/request/CreateChatRequest.kt
core/src/main/kotlin/kpring/core/chat/chat/dto/response/CreateChatResponse.kt
core/src/main/kotlin/kpring/core/chat/chatroom/client/ChatRoomClient.kt
core/src/main/kotlin/kpring/core/chat/chatroom/dto/request/CreateChatRoomRequest.kt

#44
채팅방 생성 기능을 구현했습니다
추후 다른 기능에 맞춰서 수정 예정입니다!
chat module 안에 chat이랑 chatroom 기능 두개가 같이 들어있는데 
이 경우 디렉토리 구조를
chat>chat>...
chat>chatroom>...
이렇게 하는 것이 나을까요(지금 구조)
아니면
dto>request>chat>
dto>request>chatroom>
이렇게 하는 것이 나을까요
아니면 ChatRoom module을 아예 따로 분리하는것이 나을까요?

[Chat] ChatRoom 생성 기능 구현

---

.github/workflows/pr-test.yml
auth/build.gradle.kts
auth/src/test/kotlin/kpring/auth/repository/ExpireTokenRepositoryTest.kt
chat/build.gradle.kts
chat/src/main/kotlin/kpring/chat/chat/model/Chat.kt
chat/src/test/kotlin/kpring/chat/example/SampleTest.kt
test/build.gradle.kts
test/src/main/kotlin/kpring/test/testcontainer/ContainerContextInitializer.kt
test/src/main/kotlin/kpring/test/testcontainer/SpringTestContext.kt
user/src/main/java/kpring/user/dto/request/CreateUserRequest.java
user/src/test/kotlin/kpring/user/UserApplicationTests.kt
user/src/test/kotlin/kpring/user/controller/UserControllerTest.kt
user/src/test/resources/application-test.yaml

테스트가 깨지는 경우를 수정하였습니다.
main 병합시 테스트가 성공해야만 병합할 수 있도록 action을 추가했습니다.

[Test] main PR시 테스트 실행 action 추가

---

auth/src/main/kotlin/kpring/auth/util/JwtUtil.kt
auth/src/test/kotlin/kpring/auth/service/TokenServiceTest.kt

auth test가 간혈적으로 실패하는 경우를 수정하였습니다.

[Auth] auth test 수정

---

chat/src/main/resources/application.yml
chat/src/test/kotlin/kpring/chat/example/SampleTest.kt
test/src/main/kotlin/kpring/test/testcontainer/SpringTestContext.kt

git actions test 검증 task가 실패하는 원인 중 하나가 mongodb 서버가 없었기 때문인데요.
test container를 통해서 mongodb 서버를 사용하도록 개선했습니다.

[Chat] test 실행시 mongodb 의존성으로 인한 실패 오류 해결

---

.github/workflows/pr-test.yml

> X
chore : pr-test.yml > Cache Gradle dependencies 추가하여 매 Test 별로 Gradle 을 받아오는 부분을 캐싱처리하였습니다.

[Github Actions] Cache Gradle dependencies 추가

---

user/src/main/kotlin/kpring/user/controller/FriendController.kt
user/src/main/kotlin/kpring/user/controller/LoginController.kt
user/src/main/kotlin/kpring/user/controller/UserController.kt
user/src/test/kotlin/kpring/user/controller/LoginControllerTest.kt
user/src/test/kotlin/kpring/user/controller/UserControllerTest.kt

- #51 
- #70 
ApiResponse를 적용하고, 토큰 검증 메서드를 validateToken()에서 getTokenInfo()로 변경했습니다.

[User] ApiResponse 적용

---

user/src/main/java/kpring/user/dto/request/CreateUserRequest.java
user/src/main/kotlin/kpring/user/service/UserServiceImpl.kt
user/src/main/kotlin/kpring/user/service/UserValidationService.kt
user/src/test/kotlin/kpring/user/controller/UserControllerTest.kt
user/src/test/kotlin/kpring/user/dto/request/CreateUserRequestTest.kt
user/src/test/kotlin/kpring/user/service/UserServiceImplTest.kt

- #51 
회원가입시 비밀번호 확인 로직을 삭제하였습니다.

[User] 회원가입시 비밀번호 확인 로직 삭제

---

.github/workflows/pr-test.yml
settings.gradle.kts

x
1. Build Gradle Cache 적용
> Build 시 Gradle Cache 처리할 수 있게 세팅값을 수정
2. Cache Gradle version 변경하여 성능을 끌어올리고자 함
> - 이전 : actions/cache@v3
> - 이후 : actions/cache@v4
>
> **변경이유 : Node16 이 deprecated 되었으므로 v4 사용하기를 권장
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

[Github Actions] Build Gradle Cache 적용 및 actions version 업그레이드

---

chat/build.gradle.kts
chat/src/main/kotlin/kpring/chat/chat/model/Chat.kt
chat/src/test/kotlin/kpring/chat/chatroom/ChatRoomServiceTest.kt
core/src/main/kotlin/kpring/core/global/exception/HttpClientErrorHandle.kt
core/src/test/kotlin/kpring/core/global/exception/HttpClientErrorHandleTest.kt
server/src/main/kotlin/kpring/server/adapter/output/mongo/entity/ServerEntity.kt

none
@Document를 인식하는 어노테이션 프로세서 적용으로 @Entity에 대한 의존성을 제거하였습니다.

[Chat] @Entity 의존성 제거

---

.github/workflows/pr-test.yml

- dev 브랜치에 기존 main에 적용하던 ci 작업을 추가하도록 설정을 변경하였습니다.

chore : dev 브랜치 추가로 인한 pr test 수정

---

chat/src/main/kotlin/kpring/chat/chat/api/v1/ChatController.kt
chat/src/main/kotlin/kpring/chat/chat/service/ChatService.kt
chat/src/main/kotlin/kpring/chat/chatroom/model/ChatRoom.kt
chat/src/test/kotlin/kpring/chat/chat/ChatServiceTest.kt
chat/src/test/kotlin/kpring/chat/chat/api/v1/ChatControllerTest.kt
core/src/main/kotlin/kpring/core/chat/chatroom/dto/request/CreateChatRoomRequest.kt

[Chat] 채팅 삭제 API 구현 : DELETE /api/v1/chat 

---

front/src/components/Chat/ChatRoomSideBar.tsx
front/src/components/Layout/DropDown.tsx
front/src/components/Layout/FriendsRightSideBar.tsx
front/src/components/Layout/MemberList.tsx
front/src/components/Layout/MemberListItem.tsx
front/src/components/Layout/MessageRightSideBar.tsx
front/src/components/Map/ServerMap.tsx
front/src/components/VideoCall/VideoCallBoxList.tsx
front/src/components/VideoCall/VideoCallBoxListItem.tsx
front/src/components/VideoCall/VideoCallToolBar.tsx
front/tailwind.config.js

- 코드 스타일 변경
- 1. tailwind className은 삭제후 MUI 컴포넌트의 sx속성으로 변경
- 2. rem 단위 px로 통합
- 화면공유 툴바 생성
- 화면 공유 기능은 유저 및 서버 배포 후에 완성할 계획

[Style] tailwind 에서 MUI 사용으로 코드 스타일 변경

---

infra/compose.yml

- swagger ui domain를 변경 사항을 적용했습니다.

[infra] swagger ui cluster domain 설정

---

.github/workflows/ci.yml
auth/build.gradle.kts
build.gradle.kts
infra/compose.yml
server/build.gradle.kts
server/src/main/kotlin/kpring/server/util/DtoMapper.kt
user/build.gradle.kts

- #179 
- 무료 도메인을 연결하였습니다. [domain](kpring.duckdns.org)
- main push 시 이미지 갱신할 수 있도록 github action을 추가하였습니다.
- 이미지 갱신시 버전은 깃 커밋 해시를 통해서 관리하도록 구성하였습니다.

[infra] domain 적용 및 ci actions 추가

---

user/src/main/kotlin/kpring/user/service/FriendServiceImpl.kt

- #173 
- getFriendRequests 잘못된 코드 수정

[User] 친구신청 조회 API 코드 수정

---

server/src/main/kotlin/kpring/server/adapter/output/mongo/UpdateServerPortMongoImpl.kt
server/src/test/kotlin/kpring/server/application/port/output/UpdateServerPortTest.kt

- #200 
- 서버 유저 추가시 유저가 추가되지 않는 버그를 해결했습니다.

[Server] 버그 픽스 #200

---

server/src/main/kotlin/kpring/server/adapter/output/mongo/UpdateServerPortMongoImpl.kt
server/src/test/kotlin/kpring/server/application/port/output/UpdateServerPortTest.kt

hotfix bug

---

.github/workflows/ci.yml

hotfix #209

---

front/src/App.tsx
front/src/api/token.ts
front/src/components/Auth/AuthLayout.tsx

1. 토큰이 유효할 경우, 로그인페이지와 회원가입페이지 접근시 메인으로 리디렉션됨
- 말그대로 로그인페이지나 회원가입 페이지는 현재까지 로그인이 되던 말던 접근이 늘 되었으나, 토큰이 유효할 경우 로그인페이지랑 회원가입 페이지로 접근하려고 할경우 메인 페이지로 이동하도록 했습니다

Feat/auth 토큰이 유효할 경우, 로그인페이지와 회원가입페이지 접근시 메인으로 리디렉션됨

---

auth/build.gradle.kts
server/build.gradle.kts
user/build.gradle.kts

openapi.yaml 생성시 서버 주소 프로토콜을 http -> https로 변경하였습니다.

[infra] HTTPS 적용으로 인한 api 문서 수정

---

front/src/App.tsx
front/src/components/Auth/PrivateRoute.tsx
front/src/components/Layout/LeftSideBar.tsx
front/src/store/useLoginStore.ts

1) 로그아웃 기능 추가 
- 이제 로그아웃이 됩니다. 
2) 로그인이 유효하지 않을시 로그인 페이지로 이동
- 로그인이 유효하지 않으면 메인페이지로 못갑니다..

Feat/auth 로그아웃기능 추가 + 로그인이 유효하지 않으면 로그인 페이지로 리디렉션됨

---

.github/workflows/pr-test.yml
core/src/main/kotlin/kpring/core/server/client/ServerClient.kt
server/src/main/kotlin/kpring/server/adapter/input/rest/RestApiServerController.kt
server/src/main/kotlin/kpring/server/adapter/output/mongo/GetServerProfileMongoImpl.kt
server/src/main/kotlin/kpring/server/application/port/input/GetServerInfoUseCase.kt
server/src/main/kotlin/kpring/server/application/port/output/GetServerProfilePort.kt
server/src/main/kotlin/kpring/server/application/service/ServerService.kt
server/src/main/resources/application-dev.yml
user/src/main/kotlin/kpring/user/config/AuthConfig.kt
user/src/main/kotlin/kpring/user/config/ServerConfig.kt
user/src/main/kotlin/kpring/user/controller/UserController.kt
user/src/main/kotlin/kpring/user/exception/UserErrorCode.kt
user/src/main/kotlin/kpring/user/service/UserServiceImpl.kt
user/src/main/resources/application-dev.yml
user/src/test/kotlin/kpring/user/UserApplicationTests.kt
user/src/test/kotlin/kpring/user/controller/UserControllerTest.kt
user/src/test/kotlin/kpring/user/global/CommonTest.kt

- #217 
- 로그인한 사용자가 호스트인 서버 리스트를 가져오는 API 를 구현하였습니다.
- 회원 탈퇴 API 를 구현하였습니다.
- 회원 탈퇴 Controller 테스트코드를 작성하였습니다.

[User] 회원탈퇴 API 구현

---

front/src/components/VideoCall/UserVideoComponents.tsx

> 없는 파일 import로 불러와서 프론트쪽에서 빨간 화면이 뜨기 때문에 급하게 수정해서 PR하고, 바로 머지하겠습니다.

[Fix] import 오류 수정

---

front/src/api/token.ts
front/src/components/Auth/AuthLayout.tsx
front/src/components/Auth/LoginBox.tsx
front/src/components/Auth/TokenRefreshAlert.tsx
front/src/utils/checkTokenExpiration.ts

로그인 연장 기능을 일단 만들기는 했는데... 테스트를 아직 못했어요 ^-T
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
로그인 연장 기능 구현...? 
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

[feat] 로그인 연장 기능

---

user/src/main/kotlin/kpring/user/controller/UserController.kt
user/src/main/kotlin/kpring/user/dto/request/SearchUserRequest.kt
user/src/main/kotlin/kpring/user/dto/response/UserSearchResultResponse.kt
user/src/main/kotlin/kpring/user/dto/response/UserSearchResultsResponse.kt
user/src/main/kotlin/kpring/user/repository/UserRepository.kt
user/src/main/kotlin/kpring/user/service/UserService.kt
user/src/main/kotlin/kpring/user/service/UserServiceImpl.kt
user/src/test/kotlin/kpring/user/controller/UserControllerTest.kt

- #232 
- 친구추가를 위한 사용자 검색 API 를 구현하였습니다.
- 사용자 검색 Controller 테스트코드를 작성하였습니다.

[User] 사용자 검색 API 구현

---

chat/build.gradle.kts
chat/src/main/kotlin/kpring/chat/chat/api/v1/WebSocketChatController.kt
chat/src/main/kotlin/kpring/chat/chat/model/Chat.kt
chat/src/main/kotlin/kpring/chat/chat/service/ChatService.kt
chat/src/main/kotlin/kpring/chat/global/config/WebSocketConfig.kt
chat/src/main/kotlin/kpring/chat/global/exception/ErrorCode.kt
chat/src/main/kotlin/kpring/chat/global/util/AccessVerifier.kt
chat/src/main/resources/application.yml
chat/src/main/resources/static/chat.html
chat/src/test/kotlin/kpring/chat/chat/ChatServiceTest.kt
chat/src/test/kotlin/kpring/chat/example/SampleTest.kt

close #271
기존에는 채팅방 id / 서버 id만 알면 모두 웹소켓으로 연결해서 구독할 수 있는 보안 상의 허점이 있었는데
웹소켓 연결 시부터 Interceptor를 통해 권한을 확인한 후 연결해서 보안을 강화했습니다

[Chat] Websocket Security  개선

---

chat/src/main/kotlin/kpring/chat/chat/model/Chat.kt
chat/src/main/kotlin/kpring/chat/chat/service/ChatService.kt
chat/src/main/kotlin/kpring/chat/chatroom/api/v1/ChatRoomController.kt
chat/src/main/kotlin/kpring/chat/chatroom/api/v1/WebSocketChatRoomController.kt
chat/src/main/kotlin/kpring/chat/chatroom/dto/ChatWrapper.kt
chat/src/main/kotlin/kpring/chat/chatroom/model/EventType.kt
chat/src/main/kotlin/kpring/chat/chatroom/service/ChatRoomService.kt
chat/src/main/resources/static/chatSample.html
chat/src/test/kotlin/kpring/chat/chat/ChatServiceTest.kt
chat/src/test/kotlin/kpring/chat/chatroom/ChatRoomServiceTest.kt
chat/src/test/kotlin/kpring/chat/chatroom/api/v1/ChatRoomControllerTest.kt
chat/src/test/kotlin/kpring/chat/example/SampleTest.kt
core/src/main/kotlin/kpring/core/chat/model/MessageType.kt

close #277
HTTP연결을 이용하고 있던 채팅방 Controller와 Service를 WebSocket 연결로 전환했습니다

[Chat] ChatRoomController WebSocket 연결로 전환

---

chat/src/main/kotlin/kpring/chat/chat/repository/ChatCustomRepository.kt
chat/src/main/kotlin/kpring/chat/chatroom/model/ChatRoom.kt
chat/src/main/kotlin/kpring/chat/chatroom/service/ChatRoomService.kt
chat/src/main/resources/static/chatSample.html
chat/src/test/kotlin/kpring/chat/chatroom/ChatRoomServiceTest.kt
core/src/main/kotlin/kpring/core/chat/model/ChatType.kt

- close #286 
- 채팅방에 채팅방 방장 field를 추가했습니다.

[Chat] 채팅방 방장 권한 구현

---

chat/src/main/kotlin/kpring/chat/chatroom/api/v1/WebSocketChatRoomController.kt
chat/src/main/kotlin/kpring/chat/chatroom/model/ChatRoom.kt
chat/src/main/kotlin/kpring/chat/chatroom/service/ChatRoomService.kt
chat/src/test/kotlin/kpring/chat/chatroom/ChatRoomServiceTest.kt
chat/src/test/kotlin/kpring/chat/chatroom/api/v1/ChatRoomControllerTest.kt
core/src/main/kotlin/kpring/core/chat/chat/dto/response/EventType.kt
core/src/main/kotlin/kpring/core/chat/chatroom/dto/request/TransferChatRoomOwnerRequest.kt

- close #300
채팅방 방장 권한을 위임하는 로직을 구현했습니다

[Chat] 방장 권한 위임 로직 구현 

---

chat/src/main/resources/application.yml

fix: 수정된 네이밍 컨벤션 반영

---

chat/src/main/resources/application.yml

[Infra] 배포를 위한 dev branch main branch에 병합

---

chat/src/main/resources/application.yml
user/src/main/resources/application-dev.yml

fix: server url을 infra 설정의 helm chart에 매핑된 value로 수정

---

chat/src/main/resources/application.yml
user/src/main/resources/application-dev.yml

[Infra] dev 브랜치 main으로 병합

---

user/src/main/resources/application.yaml

배포를 위해 dev 브랜치를 main 으로 병합합니다.

[Infra] dev 브랜치 main 으로 병합
